<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PeopleSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('people')->insert([
            [
                'last_names' => 'Gomez Perez',
                'first_names' => 'Juan Carlos',
                'document_type' => 'DNI',
                'document_number' => '10000001',
                'phone' => '987654321',
                'address' => 'Av. Siempre Viva 123',
                'email' => 'juan.gomez.001@example.com',
                'gender' => 'M',
                'birth_date' => '1990-05-10',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'last_names' => 'Lopez Ramirez',
                'first_names' => 'Maria Elena',
                'document_type' => 'DNI',
                'document_number' => '10000002',
                'phone' => '912345678',
                'address' => 'Jr. Las Flores 456',
                'email' => 'maria.lopez.002@example.com',
                'gender' => 'F',
                'birth_date' => '1995-08-20',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'last_names' => 'Torres Diaz',
                'first_names' => 'Luis Alberto',
                'document_type' => 'DNI',
                'document_number' => '10000003',
                'phone' => '998877665',
                'address' => 'Calle Sol 789',
                'email' => 'luis.torres.003@example.com',
                'gender' => 'M',
                'birth_date' => '1988-03-15',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'last_names' => 'Rojas Castillo',
                'first_names' => 'Ana Lucia',
                'document_type' => 'DNI',
                'document_number' => '10000004',
                'phone' => '955443322',
                'address' => 'Av. Perú 321',
                'email' => 'ana.rojas.004@example.com',
                'gender' => 'F',
                'birth_date' => '2000-11-05',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'last_names' => 'Martinez Lopez',
                'first_names' => 'Carlos Eduardo',
                'document_type' => 'DNI',
                'document_number' => '10000005',
                'phone' => '966554433',
                'address' => 'Jr. Lima 123',
                'email' => 'carlos.martinez.005@example.com',
                'gender' => 'M',
                'birth_date' => '1992-03-12',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'last_names' => 'Garcia Sanchez',
                'first_names' => 'Laura Sofia',
                'document_type' => 'DNI',
                'document_number' => '10000006',
                'phone' => '977665544',
                'address' => 'Av. Arequipa 456',
                'email' => 'laura.garcia.006@example.com',
                'gender' => 'F',
                'birth_date' => '1994-07-22',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'last_names' => 'Hernandez Ruiz',
                'first_names' => 'Miguel Angel',
                'document_type' => 'DNI',
                'document_number' => '10000007',
                'phone' => '988776655',
                'address' => 'Calle Cusco 789',
                'email' => 'miguel.hernandez.007@example.com',
                'gender' => 'M',
                'birth_date' => '1989-12-01',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'last_names' => 'Jimenez Morales',
                'first_names' => 'Isabel Cristina',
                'document_type' => 'DNI',
                'document_number' => '10000008',
                'phone' => '999887766',
                'address' => 'Jr. Trujillo 101',
                'email' => 'isabel.jimenez.008@example.com',
                'gender' => 'F',
                'birth_date' => '1996-04-18',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'last_names' => 'Perez Alvarez',
                'first_names' => 'Diego Fernando',
                'document_type' => 'DNI',
                'document_number' => '10000009',
                'phone' => '911223344',
                'address' => 'Av. Piura 202',
                'email' => 'diego.perez.009@example.com',
                'gender' => 'M',
                'birth_date' => '1991-09-30',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'last_names' => 'Ramirez Torres',
                'first_names' => 'Valentina Andrea',
                'document_type' => 'DNI',
                'document_number' => '10000010',
                'phone' => '922334455',
                'address' => 'Calle Chiclayo 303',
                'email' => 'valentina.ramirez.010@example.com',
                'gender' => 'F',
                'birth_date' => '1998-01-14',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'last_names' => 'Flores Castillo',
                'first_names' => 'Andres Jose',
                'document_type' => 'DNI',
                'document_number' => '10000011',
                'phone' => '933445566',
                'address' => 'Jr. Ica 404',
                'email' => 'andres.flores.011@example.com',
                'gender' => 'M',
                'birth_date' => '1993-06-25',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'last_names' => 'Gutierrez Vargas',
                'first_names' => 'Camila Sofia',
                'document_type' => 'DNI',
                'document_number' => '10000012',
                'phone' => '944556677',
                'address' => 'Av. Tacna 505',
                'email' => 'camila.gutierrez.012@example.com',
                'gender' => 'F',
                'birth_date' => '1997-11-08',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'last_names' => 'Reyes Mendoza',
                'first_names' => 'Javier Alejandro',
                'document_type' => 'DNI',
                'document_number' => '10000013',
                'phone' => '955667788',
                'address' => 'Calle Puno 606',
                'email' => 'javier.reyes.013@example.com',
                'gender' => 'M',
                'birth_date' => '1990-02-19',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'last_names' => 'Morales Silva',
                'first_names' => 'Gabriela Lucia',
                'document_type' => 'DNI',
                'document_number' => '10000014',
                'phone' => '966778899',
                'address' => 'Jr. Huancayo 707',
                'email' => 'gabriela.morales.014@example.com',
                'gender' => 'F',
                'birth_date' => '1995-05-03',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'last_names' => 'Ortiz Chavez',
                'first_names' => 'Roberto Carlos',
                'document_type' => 'DNI',
                'document_number' => '10000015',
                'phone' => '977889900',
                'address' => 'Av. Ayacucho 808',
                'email' => 'roberto.ortiz.015@example.com',
                'gender' => 'M',
                'birth_date' => '1987-08-27',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'last_names' => 'Delgado Rios',
                'first_names' => 'Natalia Andrea',
                'document_type' => 'DNI',
                'document_number' => '10000016',
                'phone' => '988990011',
                'address' => 'Calle Cajamarca 909',
                'email' => 'natalia.delgado.016@example.com',
                'gender' => 'F',
                'birth_date' => '1999-12-16',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'last_names' => 'Sanchez Guzman',
                'first_names' => 'Fernando Luis',
                'document_type' => 'DNI',
                'document_number' => '10000017',
                'phone' => '999001122',
                'address' => 'Jr. Lambayeque 1010',
                'email' => 'fernando.sanchez.017@example.com',
                'gender' => 'M',
                'birth_date' => '1992-10-09',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'last_names' => 'Vargas Leon',
                'first_names' => 'Monica Paola',
                'document_type' => 'DNI',
                'document_number' => '10000018',
                'phone' => '911112233',
                'address' => 'Av. Loreto 1111',
                'email' => 'monica.vargas.018@example.com',
                'gender' => 'F',
                'birth_date' => '1994-03-21',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'last_names' => 'Castro Medina',
                'first_names' => 'Eduardo Miguel',
                'document_type' => 'DNI',
                'document_number' => '10000019',
                'phone' => '922223344',
                'address' => 'Calle Amazonas 1212',
                'email' => 'eduardo.castro.019@example.com',
                'gender' => 'M',
                'birth_date' => '1988-07-04',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'last_names' => 'Romero Aguilar',
                'first_names' => 'Patricia Elena',
                'document_type' => 'DNI',
                'document_number' => '10000020',
                'phone' => '933334455',
                'address' => 'Jr. San Martin 1313',
                'email' => 'patricia.romero.020@example.com',
                'gender' => 'F',
                'birth_date' => '1996-09-13',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'last_names' => 'Ruiz Navarro',
                'first_names' => 'Antonio Jose',
                'document_type' => 'DNI',
                'document_number' => '10000021',
                'phone' => '944445566',
                'address' => 'Av. Junin 1414',
                'email' => 'antonio.ruiz.021@example.com',
                'gender' => 'M',
                'birth_date' => '1991-01-26',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'last_names' => 'Mendoza Soto',
                'first_names' => 'Silvia Maria',
                'document_type' => 'DNI',
                'document_number' => '10000022',
                'phone' => '955556677',
                'address' => 'Calle Ancash 1515',
                'email' => 'silvia.mendoza.022@example.com',
                'gender' => 'F',
                'birth_date' => '1998-04-07',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'last_names' => 'Guerrero Ponce',
                'first_names' => 'Ricardo Alberto',
                'document_type' => 'DNI',
                'document_number' => '10000023',
                'phone' => '966667788',
                'address' => 'Jr. La Libertad 1616',
                'email' => 'ricardo.guerrero.023@example.com',
                'gender' => 'M',
                'birth_date' => '1993-11-18',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'last_names' => 'Herrera Vega',
                'first_names' => 'Daniela Sofia',
                'document_type' => 'DNI',
                'document_number' => '10000024',
                'phone' => '977778899',
                'address' => 'Av. Ucayali 1717',
                'email' => 'daniela.herrera.024@example.com',
                'gender' => 'F',
                'birth_date' => '1997-06-29',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'last_names' => 'Medina Rojas',
                'first_names' => 'Oscar Eduardo',
                'document_type' => 'DNI',
                'document_number' => '10000025',
                'phone' => '988889900',
                'address' => 'Calle Madre de Dios 1818',
                'email' => 'oscar.medina.025@example.com',
                'gender' => 'M',
                'birth_date' => '1990-08-11',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'last_names' => 'Cabrera Luna',
                'first_names' => 'Veronica Andrea',
                'document_type' => 'DNI',
                'document_number' => '10000026',
                'phone' => '999990011',
                'address' => 'Jr. Tumbes 1919',
                'email' => 'veronica.cabrera.026@example.com',
                'gender' => 'F',
                'birth_date' => '1995-12-02',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'last_names' => 'Vega Torres',
                'first_names' => 'Roberto Carlos',
                'document_type' => 'DNI',
                'document_number' => '10000027',
                'phone' => '911112233',
                'address' => 'Av. Libertad 2020',
                'email' => 'roberto.vega.027@example.com',
                'gender' => 'M',
                'birth_date' => '1985-03-14',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'last_names' => 'Luna Morales',
                'first_names' => 'Sofia Isabel',
                'document_type' => 'DNI',
                'document_number' => '10000028',
                'phone' => '922223344',
                'address' => 'Calle Union 2121',
                'email' => 'sofia.luna.028@example.com',
                'gender' => 'F',
                'birth_date' => '1992-07-25',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'last_names' => 'Ponce Reyes',
                'first_names' => 'Diego Alejandro',
                'document_type' => 'DNI',
                'document_number' => '10000029',
                'phone' => '933334455',
                'address' => 'Jr. Bolivar 2222',
                'email' => 'diego.ponce.029@example.com',
                'gender' => 'M',
                'birth_date' => '1988-11-30',
                'created_at' => now(),
                'updated_at' => now()
            ]
        ]);
    }
}